name: Deploy Ubuntu Server Project

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add SSH private key to agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}  # Ensure this secret contains the correct private key

      - name: Check SSH key loaded into agent
        run: |
          ssh-add -l  # Lists the SSH keys loaded into the agent
          # Make sure the correct key is listed here

      - name: Ensure known_hosts file exists
        run: |
          mkdir -p ~/.ssh
          touch ~/.ssh/known_hosts  # Ensure known_hosts file exists

      - name: Add SSH Host Key to known_hosts
        run: |
          ssh-keyscan -p 9988 $SSH_HOST >> ~/.ssh/known_hosts  # Add the host key for the correct port

      - name: Deploy to Server
        env:
          SERVER_USER: ${{ secrets.SSH_USER }}
          SERVER_IP: ${{ secrets.SSH_HOST }}
          APP_DIR: ${{ secrets.WORK_DIR }}
        run: |
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=~/.ssh/known_hosts -p 9988 $SERVER_USER@$SERVER_IP "
          cd $APP_DIR &&
          git remote set-url origin git@github.com:mineppl12/newplma.git &&  # Make sure this is the SSH URL, not HTTPS
          git pull origin main &&
          npm install &&
          npm run build
          "
