name: Deploy Ubuntu Server Project

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add SSH key for server
        env:
          SERVER_IP: ${{ secrets.SSH_HOST }}
        run: |
          ssh-keyscan -p 9988 $SERVER_IP >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      - name: Add SSH private key to agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Server
        env:
          SERVER_USER: ${{ secrets.SSH_USER }}
          SERVER_IP: ${{ secrets.SSH_HOST }}
          APP_DIR: ${{ secrets.WORK_DIR }}
        run: |
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=~/.ssh/known_hosts -p 9988 $SERVER_USER@$SERVER_IP "
          cd $APP_DIR &&
          git remote set-url origin git@github.com:mineppl12/newplma.git &&
          git pull origin main &&
          npm install &&
          npm run build
          "
